version: '3.8'

services:
  db:
    image: postgres:13
    container_name: blinds-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blinds_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: node:18
    container_name: blinds-app
    command: sh -c "npm install && npm run prisma-generate && npm run dev"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/blinds_management
      DISABLE_ERD: true
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
